### ISSUE TITLE
Come up with better name

### ISSUE THREAD

**Issue by yor42** [yor42/projectazure_forge#10]
Project Azure sounds like lazy placeholder name (and it is)

**Comment by Ihaveabigschlong69420** [comment]
Project: Waifu Wars

**Comment by yor42** [comment]
this is not about PVP and combat main.
Im trying to make it tech focused

**Comment by Ihaveabigschlong69420** [comment]
> this is not about PVP and combat main.
> Im trying to make it tech focused

Project: Get the fuck back to the kitchen you lazy woman

**Comment by yor42** [comment]
:concern:

**Comment by yor42** [comment]
this will only be meme debate.  if I leave this open. closed.
