### ISSUE TITLE
Why is there no fate waifu's

### ISSUE THREAD

**Issue by Ihaveabigschlong69420** [yor42/projectazure_forge#11]
The fact that there is no fate waifus is outrageous and outright stupid, i demand that they be added immediately.

**Comment by yor42** [comment]
because this mod is too barebone and have so much things to be done first before adding more mob

**Comment by Ihaveabigschlong69420** [comment]
> because this mod is too barebone and have so much things to be done first before adding more mob

Yes it's a joke

**Comment by yor42** [comment]
[Insert I know meme here]
