### ISSUE TITLE
project_azure-0.3.7.2 Shipgirl AI seems to not use their rigging guns

### ISSUE THREAD

**Issue by Bakaistic** [yor42/projectazure_forge#16]
Shipgirl AI seem to not use their rigging guns at all. Torpedos do work, but the rigging guns do not. I've even loaded my girl's ammo slots but i've not gotten my girls to shoot their single 127MM's that are on the rigging

**Comment by yor42** [comment]
Should be working as intended because ships only fire in sea(or it wouldnt make much sense of having other entity)
