### ISSUE TITLE
project_azure-0.3.7.2 Crashed when attempting to power recruit beacon

### ISSUE THREAD

**Issue by Bakaistic** [yor42/projectazure_forge#20]
[crash-2021-12-28_01.36.00-server.txt](https://github.com/yor42/projectazure_forge/files/7783232/crash-2021-12-28_01.36.00-server.txt)

yeah uh..oops. I also put materials in it as well. I feel this thing is still a bit incomplete though so ignore maybe? I did use a creative power source, but i think it shouldnt matter

**Comment by yor42** [comment]
Fixed with 886b44c
